# Generated by Django 3.1.1 on 2020-09-21 10:07

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('kind', models.CharField(choices=[('lecture', 'лекция'), ('stream', 'стрим'), ('tsumego_answer', 'ответ на задачу'), ('review', 'разбор')], default='stream', max_length=20, verbose_name='Тип')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('sgf', models.FileField(blank=True, null=True, upload_to='', verbose_name='СГФ файл')),
            ],
            options={
                'verbose_name': 'Титул',
                'verbose_name_plural': 'Титулы',
            },
        ),
    ]
