# Generated by Django 3.1.1 on 2020-09-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AddField(
            model_name='video',
            name='date',
            field=models.DateField(verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='sgf',
            field=models.FileField(blank=True, null=True, upload_to='sgf', verbose_name='СГФ файл'),
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(related_name='tag_videos', to='videos.Tag', verbose_name='Тэги'),
        ),
    ]
