# Generated by Django 2.2.5 on 2019-11-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_squashed_0007_auto_20191104_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='challenger',
            field=models.BooleanField(default=False, verbose_name='Претендент'),
        ),
        migrations.AddField(
            model_name='participant',
            name='title_holder',
            field=models.BooleanField(default=False, verbose_name='Держатель титула'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='point_for_game',
            field=models.FloatField(default=0, verbose_name='Очки за партию'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='point_for_win',
            field=models.FloatField(default=0.04, verbose_name='Очки за победу'),
        ),
    ]
