# Generated by Django 2.2.9 on 2020-01-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_game_time_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='kind',
            field=models.CharField(choices=[('liga', 'лига'), ('all', 'круговая')], default='all', max_length=10, verbose_name='Тип'),
        ),
    ]
