# Generated by Django 2.2.9 on 2020-01-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_title_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='rank',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Ранг'),
        ),
        migrations.AlterField(
            model_name='title',
            name='kind',
            field=models.CharField(choices=[('liga', 'лига'), ('all', 'круговая'), ('group', 'групповая лига')], default='all', max_length=10, verbose_name='Тип'),
        ),
    ]
