# Generated by Django 2.2.5 on 2019-10-11 15:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tsumego', '0003_auto_20190923_1609'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tsumego',
            unique_together={('date', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='tsumegoresult',
            unique_together={('tsumego', 'user')},
        ),
    ]
